minify: true
scheme: Gemini
darkmode: true
menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
social:
  GitHub: 'https://github.com/letianzhang || fab fa-github'
  E-Mail: 'mailto:15142334091@@163.com || fa fa-envelope'
footer:
  icon:
    animated: true
symbols_count_time:
  separated_meta: true
  item_text_total: true
related_posts:
  enable: true
  display_in_home: true
reading_progress:
  enable: true
  color: '#37c6c0'
  height: 2px
bookmark:
  enable: false
  color: '#222'
  save: auto
github_banner:
  enable: true
  permalink: 'https://github.com/letianzhang'
  title: Follow me on GitHub
baidu_site_verification: code-aL6aaiBAm7
bing_site_verification: A1C6117723A31C8FD11394376EDBD912
valine:
  enable: true
  appId: M0ei5nSCqRVPKskpWOrsLGrk-gzGzoHsz
  appKey: HPK3Gox3VjWAuSGMTxQD0d2g
tag_icon: true
rating:
  enable: true
  id: 27248
  color:  "#fc6423"
chatra:
  enable: true
  async: true
  id: YcinC4Y22MCgKXNTt
chat:
  enable: true
  service: chatra
  icon: fa fa-comment
  text: Chat
